### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by luator** [CallmeNezha/SimpleDBSCAN#2]
In the README, there is the line

> There is no license here, hope you like it :)

which I interpret the way that you are generally okay with people using this code.
However, legally "no license" means others are not allowed to do anything with it (see, for example, [here](https://choosealicense.com/no-permission/)).

If your intention is really to allow others to use the code, please add an open source license.  If you are not sure which license to choose, https://choosealicense.com/ may help.

**Comment by luator** [comment]
I

**Comment by luator** [comment]
(sorry for closing and reopening, I pressed the wrong button...)

**Comment by WanpengQian** [comment]
a MIT license will be great! ;-)

**Comment by MattEding** [comment]
Based on the comment "There is no license here, hope you like it", I think you should choose either the [Unlicense](https://en.wikipedia.org/wiki/Unlicense), [CC0](https://en.wikipedia.org/wiki/Creative_Commons_license#Zero_/_public_domain), or [any of the other public domain licenses](https://en.wikipedia.org/wiki/Public-domain-equivalent_license) for this project.

**Comment by drdanz** [comment]
"There is no license here" technically means that you do not give a license to use your software to anyone, so no, we don't like it, because we cannot use it, sorry... 😉 

As explained [here](https://choosealicense.com/no-permission/) if you don't include a license, *your work is under exclusive copyright by default*, which means that **nobody is allowed to use your library**, neither in open source, nor in commercial software.

Unless that's your intention, you should seriously consider to add one license as suggested by the others.

**Comment by CallmeNezha** [comment]
Sorry for my late response, I have already add the MIT license in README. Thanks a lot.
