### ISSUE TITLE
Is this code fast?

### ISSUE THREAD

**Issue by ArtlyStyles** [CallmeNezha/SimpleDBSCAN#3]
I have 8K data points, each one is 4 dimension. How lone does it take to clustering?

**Comment by CallmeNezha** [comment]
It's quite popular to use kdtree included in this library. According to kdtree algorithm, its O(log(n)) in average and O(n) in the worst case. Rest of the code is pure simple C++, but not using any SIMD(SSE) CPU instruction boost or OpenMP etc., because i would like to keep it simple and comprehensive also dependency free; just like the prefix name of library 'Simple'. And indeed it is not performance benchmarked broadly because i dont have a lot machines in-hand, but it's quite simple to test its performance on your own machine if you really want to try it. 😀
