### ISSUE TITLE
why it is slower than sklearn DBSAN?

### ISSUE THREAD

**Issue by zhangyu13141** [CallmeNezha/SimpleDBSCAN#8]

**Comment by CallmeNezha** [comment]
I did not compare this library's performance with sklearn's DBSCAN, nor do I intend to. Because this library is a very straightforward implementation of the DBSCAN algorithm, with no platform-specific or CPU-specific performance tuning. As far as I know, sklearn is already accelerated using math libraries like BLAS, using CPU functions like SIMD, so... If you like one header file inclueded DBSCAN, you can use this library cleanly and safely, if your software already uses the sklearn library heavily, maybe you should stick with it.
